#!/usr/bin/env sh

#  /$$$$$$$   /$$$$$$
# | $$__  $$ /$$__  $$
# | $$  \ $$| $$  \ $$
# | $$  | $$| $$  | $$
# | $$  | $$| $$$$$$$/
# |__/  |__/| $$____/
#           | $$
#           | $$
#           |__/ 
#
# np - a very simple notepad for unix users
#
# configuration: add this to your .profile
# export NP_NOTEPAD_LOCATION=$HOME/your_dir
# export NP_AUTHOR_NAME="Your Name Here";
# export NP_NOTEPAD_NAME="Notepad";

usage(){
	echo "np - a very simple notepad for unix users";
	echo "Usage:";
	echo "  edit,     e :  opens today's notepad";
	echo "  publish,  p :  publishes entire series as pdf";
	echo "  list,    ls :  lists all notepads";
	echo "  config,  rc :  print your config";
}

get_config(){
	if [[ -z "${NP_NOTEPAD_LOCATION}" ]]; then
		NOTEPAD_LOCATION="~/.notepad";
	else
		NOTEPAD_LOCATION="${NP_NOTEPAD_LOCATION}"
	fi;

	if [[ -z "${NP_AUTHOR_NAME}" ]]; then
		AUTHOR_NAME=$(whoami);
	else
		AUTHOR_NAME="${NP_AUTHOR_NAME}"
	fi;

	if [[ -z "${NP_NOTEPAD_NAME}" ]]; then
		NOTEPAD_NAME="Notepad";
	else
		NOTEPAD_NAME="${NP_NOTEPAD_NAME}"
	fi;
}

print_config(){
	echo "Notepad location: $NOTEPAD_LOCATION";
	echo "Author name:      $AUTHOR_NAME";
	echo "Notepad name:     $NOTEPAD_NAME";
}

main() {
	get_config;

	case $1 in
		'edit' | 'e')
			edit
			;;
		'publish' | 'p')
			publish
			;;
		'list' | 'ls' )
			list
			;;
		'config' | 'rc' )
			print_config
			;;
		*)
			usage
			;;
	esac
}

edit() {
	if [ ! -d $NOTEPAD_LOCATION ]; then
		mkdir -p $NOTEPAD_LOCATION;
	fi;

	if [ ! -f $NOTEPAD_LOCATION/$(date +'%y%m%d').md ]; then
		cat << EOF > $NOTEPAD_LOCATION/$(date +'%y%m%d').md
# $(date +"%A %d %B, %Y")

---
EOF
	fi;

	$EDITOR $NOTEPAD_LOCATION/$(date +'%y%m%d').md;
}

publish() {
	mkdir -p $NOTEPAD_LOCATION/generated;
	cat << EOF > $NOTEPAD_LOCATION/generated/front.md
---
title:
- "${NOTEPAD_NAME}"
author:
- "${AUTHOR_NAME}"
fontsize:
- 12pt
papersize:
- a5
geometry:
- margin=0.5in
---

\maketitle
\thispagestyle{empty}
\clearpage
\tableofcontents
\pagenumbering{roman}
\clearpage
\pagenumbering{arabic}
\setcounter{page}{1}

# About

This is a notepad built by [np](https://github.com/joefg/np), generated on $(date +"%A %d %B, %Y").

It is comprised of entries found inside the author's \`$NOTEPAD_LOCATION\` directory.

---

\clearpage


EOF

	if ! command -v pandoc &> /dev/null
	then
		echo "Pandoc is not installed on this system.";
	else
    cd $NOTEPAD_LOCATION
		pandoc $NOTEPAD_LOCATION/generated/front.md \
			$(list) \
			-o $NOTEPAD_LOCATION/generated/notepad.pdf;

		echo "PDF generated at $NOTEPAD_LOCATION/generated/notepad.pdf";
	fi
}

list() {
	find $NOTEPAD_LOCATION -type f -name "*.md" -not -path "*/generated/*" -not -path "*/drafts/*" \
		-exec ls -1 "{}" +;
}

main "$@"
